### PR TITLE
US142 - split po files

### PR DESCRIPTION
**Pull request by mewtaylor**
This splits up our language .po files into two separate ones - one that contains translations for the UI of the website, and one for the Documentation of how to use the website (i.e. the Tips window).

### CODE REVIEW

**Comment by leoburd** [comment]
I understand this might open a whole new batch of issues, but would there be any way for translators to test the Tips window strings offline, just like they do for the blocks?

**Comment by rschamp** [comment]
@leoburd That is difficult to do without giving them access to the scratchr2 repository and setting them up with our Django development process. This is because the tips window is translated by exporting the html files out of scratchr2, "baking" the translations into the html, rather than dynamically replacing the translations like happens with the blocks.  Of course it is possible, but like you say it would open a whole batch of issues to accomplish.

**Comment by rschamp** [comment]
@mewtaylor Not sure if we came to a conclusion about adding the LC_MESSAGES subdirectory here — can we add that before merging?  Otherwise LGTM (kind of hard to review, so I'll take your word for it :) )

**Comment by mewtaylor** [comment]
Oh right - I'm fine with it! But I want to check with @sayamindu about the UI part of it. @sayamindu, do you think it would be confusing for translators to see the extra level of `LC_MESSAGES` when they go into a project's .po files?

**Comment by rschamp** [comment]
If it is confusing, we could set up the symlinks the other way around, so that it doesn't appear to be there in Pootle, but is there for Django — like a second directory set up with symlinks, which Pootle uses, and then Django uses the actual directory. e.g.:

```
documentation/
    ab/
        LC_MESSAGES/
            django.po
    ....

documentation-pootle/
    ab -> ../documentation/ab/LC_MESSAGES/
    ...
```

Or yet another way, we leave it as is for Pootle, and set up the second directory for Django, which symlinks LC_MESSAGES to the Pootle directory for the language:

```
documentation/
    ab/
        django.po

documentation-django/
    ab/
        LC_MESSAGES -> ../../documentation/ab/
```

**Comment by mewtaylor** [comment]
I like the second option! But I'll wait to hear what others think about the added layer, since it would be more ideal just to have it if it's not too big a deal.

**Comment by rschamp** [comment]
I just realized the second option is impossible since documentation-django would be a submodule, so if its contents were just symlinks, it would kind of be useless...

**Comment by mewtaylor** [comment]
Ah I was wondering about that - also, I'm wondering if that means that we'll have trouble with symlink-ing in general, since the plan is to symlink the project directories into the `scratchr2_translations` repo stored elsewhere anyways.

**Comment by rschamp** [comment]
We can link into the submodule from the parent, like we always did with djangobb in scratchr2.

**Comment by sayamindu** [comment]
It would be nice to avoid LC_MESSAGES (as there's always a chance that translators may upload the file directly to the upper level as a sibling of LC_MESSAGES, causing our scripts to not find the updated file). However, if avoiding it is too much of a trouble, it's fine.

**Comment by mewtaylor** [comment]
avoid would just mean we either decide to live with `makesymlinks`, or we replace it with symlinks on Pootle as @rschamp mentioned. Any thoughts there?

Also @sayamindu aside from `LC_MESSAGES`, are this and https://github.com/LLK/scratchr2/pull/2419 looking okay to you? You had some questions there that I tried to answer.

**Comment by rschamp** [comment]
We don't really want to live with makesymlinks since it leads to an infinite filepath, hence LLK/scratchr2#1882

**Comment by sayamindu** [comment]
Symlinks on Pootle sounds fine (especially since we are not allowing translators to commit to repositories directly).

**Comment by mewtaylor** [comment]
Great - so what I'll do is:
1. Pull translations from Pootle for the website project
2. Remove the website project from the Pootle interface (but keep a copy)
3. Merge the newest translations into this branch (and add back in the `LC_MESSAGES` directory)
4. Commit those changes
5. Merge this branch into master
6. Create two new projects on Pootle for ui and documentation
7. Pull the new changes to the Pootle server
8. Create the symlinks
9. Update Jenkins tasks as needed

Anything I'm missing?

**Comment by sayamindu** [comment]
Sounds good. To be safe, you may want to shut down Pootle for a subset of the steps you outlined above.

**Comment by mewtaylor** [comment]
Ok - I'll get in touch with Natalie about it

**Comment by ntlrsk** [comment]
Thanks for the heads-up. What shall I write to translators? (Feel free to move this 

We will be upgrading the translation site to separate the help files (including the tips and tutorials) from the rest of the website.  The site will be temporarily shut down on Friday May 1 (?).

You will be able to make updates to translation from Saturday May 2 to Tuesday evening May 6 (Eastern US time).  ???

**Pull request merged**
